### ISSUE TITLE
Install failed at line 63

### ISSUE THREAD

**Issue by jtlacci** [codfish/dotfiles#9]
`sh: line 63: /Users/john/.dotfiles/oh-my-zsh-custom/00-dotfiles.zsh: No such file or directory`

I had ohmyzsh install previously so not sure if conflict

**Comment by codfish** [comment]
@jtlacci hmm, this file gets created when you install: https://github.com/codfish/dotfiles/blob/master/install.sh#L64

```sh
# store DOTFILES_REPO env var in custom zsh script for syncing later
echo "export DOTFILES_REPO=${DOTFILES_REPO}" > $ZSH_CUSTOM/00-dotfiles.zsh
```

this line always runs, so that file should def exist. `$ZSH_CUSTOM` gets set at the top of install like so:

```sh
DOTFILES="${HOME}/.dotfiles"
ZSH="$DOTFILES/oh-my-zsh"
ZSH_CUSTOM="${DOTFILES}/oh-my-zsh-custom"
```

no real logic here, we're explicitly setting these paths. You definitely followed the [steps here](https://github.com/codfish/dotfiles/wiki/Migrating-from-the-bash-dotfiles-to-the-new-Zsh-dotfiles), including deleting your existing dotfiles?

**Comment by jtlacci** [comment]
That worked
